/* Generated by Together */

package bank.exceptions;

public class NumberDoesntExistException extends Exception {
    /**
     *
     */
    private static final long serialVersionUID = 1440942789246305013L;

    public NumberDoesntExistException(String message) {
        super(message);
    }
}
